[project]
name = "magister"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "meshio>=5.3.5",
    "scipy>=1.15.2",
    "vtk>=9.4.1",
]
